# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  S3_BUCKET_NAME: "fallout-builds"

stages:
  - build
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache setupCiWorkspace build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - build/libs/Fallout_Equestria*[0-9].jar
    expire_in: 2 week


deploy:
  stage: deploy
  script: gradle ftp -PFTPUserName=$FTPUserName -PFTPdir=$FTPdir -PFTPPassword=$FTPPassword
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - deploy


after_script:
- echo "End CI"




