image: java:8-jdk

cache:
  paths:
    - gradle/wrapper
    - gradle/caches

stages:
  - build

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew setupCiWorkspace jar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master


after_script:
- echo "End CI"