image: java:8-jdk

stages:
  - build

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew setupCiWorkspace jar
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}" 
    paths:
      - build/libs/*.jar
    expire_in: 2 week
  only:
    - master


after_script:
- echo "End CI"